# Creating the Customer Objection Classification Dataset

In [5]:
import os
import pandas as pd

# Define the categories
categories = {
    'Refurbishment Quality': '1',
    'Car Issues': '2',
    'Price Issues': '3',
    'Customer Experience Issues': '4',
    'No Label': '5'
}

def extract_label_from_filename(filename):
    """Extract the label from the filename."""
    for category in categories.keys():
        if category.replace(' ', '_') in filename:
            return category
    return 'Unknown'  # Handle cases where the label isn't found

def load_labeled_data(data_dir):
    """Load labeled data from text files into a DataFrame."""
    data = {'text': [], 'label': []}
    
    for filename in os.listdir(data_dir):
        if filename.endswith('.txt'):
            # Extract label from the filename
            label = extract_label_from_filename(filename)
            
            # Read the file content
            file_path = os.path.join(data_dir, filename)
            with open(file_path, 'r', encoding='utf-8') as file:
                text = file.read().strip()
            
            data['text'].append(text)
            data['label'].append(label)
    
    # Create DataFrame
    df = pd.DataFrame(data)
    return df

In [6]:
data_dir = r'C:\Users\haris\Documents\Programming\Hackathons\NIRAL\labeled_data'  # Replace with your directory path
df = load_labeled_data(data_dir)

# Save DataFrame to a CSV file
output_csv = r'C:\Users\haris\Documents\Programming\Hackathons\NIRAL\labeled_data.csv'  # Replace with your output file path
df.to_csv(output_csv, index=False)
df

                                                  text                  label
0    Salesperson: Yes, let me confirm. The starting...             Car Issues
1    Customer: Sir?\nSalesperson: It has been leake...             Car Issues
2    Salesperson: It's one lakh per year. In one ye...             Car Issues
3    Salesperson: This one is priced at Rs. 6,97,00...             Car Issues
4    Salesperson: Absolutely. Here it is.\nCustomer...             Car Issues
..                                                 ...                    ...
277  Salesperson: By the way, what's the main issue...           Price Issues
278  Salesperson: Don't worry. We handle all the pa...           Price Issues
279  Customer: Sir, you have to repaint it.\nSalesp...  Refurbishment Quality
280  Salesperson: Ah, I see. The car number is 7064...  Refurbishment Quality
281  Salesperson: The price includes one service be...  Refurbishment Quality

[282 rows x 2 columns]